### ISSUE TITLE
Link to multipleAPA annotation files

### ISSUE THREAD

**Issue by khourhin** [vodkatad/roar#1]
Hi !
I would like to retrieve the annotations files for MultipleAPA but the link provided in the vignette is not responsive:
[http://94.91.177.36:6638/roar/](http://94.91.177.36:6638/roar/)

Could you please specify another location where to find these annotation files ?

Thanks !

Etienne

**Comment by vodkatad** [comment]
Woops, sorry - I need to update the vignette. In the meanwhile you can find gtf files for multiple and single APA analyses here: https://github.com/vodkatad/roar/wiki/Identify-differential-APA-usage-from-RNA-seq-alignments

**Comment by khourhin** [comment]
Great, thanks !
E
