### ISSUE TITLE
Disagreement while manually checking "roar" count numbers

### ISSUE THREAD

**Issue by mantvydasl** [vodkatad/roar#2]
I am experiencing some strange behavior when counting the number of reads from BAM files for the POST and PRE regions.

I have been using the package for a past couple of weeks and it looks really promising.
However when trying to compare the returned read counts from roar with the reads counted via "IGV viewer" or "samtools" I am getting a few discrepancies.

The situation is like this: the genes with non-zero reads returned from roar match correctly with the reads in our manual inspection of the BAM files.
However some of the genes where roar returns 0s for both PRE and POST regions seem to contain quite a lot of reads within the actual BAM files.

I tried using a few different APA annotation files but in all cases observed the same problem.

Is this a potential bug. Or maybe roar discards any regions/reads based on some internal criteria?

**Comment by vodkatad** [comment]
First of all sorry for the delay, I lost the email with the notice somehow :/
If the reads overlap more than one PRE/POST region of different genes they are discarded, I need to check  summarizeOverlaps (the function that I am using to count reads) for details on overlapping considerations, I use the default 'Union' mode that should discard all overlapping reads.
Do the 0s reported by roar correspond to regions where there are nearby PRE and POST regions of other genes?

**Comment by vodkatad** [comment]
First of all sorry for the delay, I lost the email with the notice somehow :/ Thanks for using roar and for reporting possible bugs!
If the reads overlap more than one PRE/POST region of different genes they are discarded, I need to check  summarizeOverlaps (the function that I am using to count reads) for details on overlapping considerations, I use the default 'Union' mode that should discard all overlapping reads.
Do the 0s reported by roar correspond to regions where there are nearby PRE and POST regions of other genes?

**Comment by mantvydasl** [comment]
Thank you for reply. 
I was able to figure out what went wrong. We had APA annotation files with duplicate gene identifiers. As a result all the reads of these genes were discarded.

**Comment by vodkatad** [comment]
It's nice that you figured it out (duplicated genes would definitely cause discarded reads), sorry for being late, I'll monitor github issues more closely :)
