### ISSUE TITLE
How to read the local bam file

### ISSUE THREAD

**Issue by Trandamere** [vodkatad/roar#3]
Hello:
I am very interested in the software you developed.But my R foundation is terrible. 
```
bamTreatment <- RNAseqData.HNRNPC.bam.chr14_BAMFILES[seq(5,8)]
```
I stayed at this step for a long time on how to read the bam file.
The syntax of R is too difficult to operate.

**Comment by Trandamere** [comment]
E:\luping\LncRNA\ISO-RNA-Seq\Hy1.bam
like this file,How to load it?
Thanks

**Comment by vodkatad** [comment]
Sorry for the delay - the example you cited from the vignette accesses two elements from a list of alignment objects.
For local files you have to use RoarDatasetFromFiles, so if you have Hy1.bam and (for example) Hy2.bam
with alignments from the two conditions that you want to compare:
rds <- RoarDatasetFromFiles(list('E:\luping\LncRNA\ISO-RNA-Seq\Hy1.bam'), list(E:\luping\LncRNA\ISO-RNA-Seq\Hy2.bam'), 'pathToGtf')

**Comment by Trandamere** [comment]
Hi:
Thank you for your reply.
Does the comment for the gtf file contain only the end exon?

**Comment by vodkatad** [comment]
It has intervals for the "PRE" and  "POST" regions - they are on the last two or more exons depending on where the 3'UTR is annotated on refseq and the APA site in the two databases. In the majority of cases the POST is on the last one, while we define the PRE up to the beginning of the previous exon.

**Comment by Trandamere** [comment]
What type of annotation？
![1](https://user-images.githubusercontent.com/24996924/65860992-03d2df00-e39e-11e9-85c3-d4f08c41596e.png)

**Comment by vodkatad** [comment]
Second one!

**Comment by Trandamere** [comment]
Hi：
Does the  PRE UTR part contain exons? Or is only the UTR part being used?

**Comment by Trandamere** [comment]
Hi：
Is the PRE initial part from the end of the CDS or the last exon?

**Comment by vodkatad** [comment]
See the section "Definition of PRE and POST portion"  -  https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-016-1254-8#Sec2
The PRE contains the whole exon with the APA site being considered.

**Comment by Trandamere** [comment]
Thank you!

**Comment by Trandamere** [comment]
Hi：
How to write gff file for the multiple APA version ?
Is it using the same gene ID and different regions?

**Comment by Trandamere** [comment]
？

**Comment by Trandamere** [comment]
Hi:
Why do I get an error when I use the 'RoarDatasetFromFiles', but I normally read the file when I use the 'RoarDatasetMultipleAPAFromFiles'?
The command line is exactly the same.

```
rds <- RoarDatasetFromFiles(list(
'E:/disk3/aging-0-48h/bam/Hyp12h-1.bam',
'E:/disk3/aging-0-48h/bam/Hyp12h-2.bam'),
list(
'E:/disk3/aging-0-48h/bam/Hyp0h-1.bam',
'E:/disk3/aging-0-48h/bam/Hyp0h-2.bam'),
'C:/Users/lp/Desktop/roar5.gtf')

Error in order(datastate$c) : argument 1 is not a vector
Error in order(datastate$c) : argument 1 is not a vector
```
