### ISSUE TITLE
roar on replicates RNA-Seq samples "polyA+ unstranded dataset"

### ISSUE THREAD

**Issue by JamalEH** [vodkatad/roar#5]
Dear team,

Thank you for the great tool roar!

I'm welling to try your tool on my RNA-Seq dataset for the purpose of identifying genes with a differential usage of pA sites.

I have a polyA+, paired-end, unstranded, RNA-Seq dataset performed in 2 conditions 3 replicates each.

is it possible to run roar on replicates RNA-seq samples?

Thank you so much in advance!
Kind regards,
Jamal.

**Comment by JamalEH** [comment]
solved!

**Comment by vodkatad** [comment]
Sorry for the delay, glad to hear that it's solved (it should definitely be possible!)
